### ISSUE TITLE
How to setup firebase

### ISSUE THREAD

**Issue by dog1cool** [thurdev/AyxBot#2]
How do you setup firebase i am so confused

**Comment by thurdev** [comment]
go to https://console.firebase.google.com, create your project then:

![image](https://user-images.githubusercontent.com/34294813/125920359-f97dd9e0-03e6-44d4-90c2-ef0979a92aff.png)

![image](https://user-images.githubusercontent.com/34294813/125920701-515c88d5-467c-471a-9367-56c46a946fd0.png)

![image](https://user-images.githubusercontent.com/34294813/125920802-550da01e-e11e-4703-9529-d29eb2253ad1.png)

in the next step choose the best region for you

![image](https://user-images.githubusercontent.com/34294813/125920994-df692345-808f-4f2f-9c51-34be54a3d3af.png)

![image](https://user-images.githubusercontent.com/34294813/125921082-87fd0d21-226f-438e-8faf-1dadd9e3bc30.png)

![image](https://user-images.githubusercontent.com/34294813/125921093-d36e7cc6-b65c-4ea0-aa2e-6b99ea4c1fce.png)

![image](https://user-images.githubusercontent.com/34294813/125921118-f9fbe72b-b48c-4015-b1d9-62ed98f1e23d.png)

copy the data inside the downloaded file, and paste in serviceAccount.json
