### ISSUE TITLE
Module missing ! 

### ISSUE THREAD

**Issue by darkhacknet** [thurdev/AyxBot#9]
Hey bro hope you're well !

Please help me with this issue. I'm receiving this 

─$ node .       
module.js:491
    throw err;
    ^

Error: Cannot find module './handlers/command'
    at Function.Module._resolveFilename (module.js:489:15)
    at Function.Module._load (module.js:439:25)
    at Module.require (module.js:517:17)
    at require (internal/module.js:11:18)
    at __dirname.forEach.handler (/home/xborland/AyxBot/index.js:35:5)
    at Array.forEach (<anonymous>)
    at Object.<anonymous> (/home/xborland/AyxBot/index.js:34:13)
    at Module._compile (module.js:573:30)
    at Object.Module._extensions..js (module.js:584:10)
    at Module.load (module.js:507:32)

when ... node .

I was researching about this but seems to be simple but with no precise solution . 
hope that you can help. 

Thanks !

**Comment by thurdev** [comment]
Hello, I checked the code and actually I didn't uploaded the handlers folder.

Basically you have to create a simple command handler, tell me if you need help with this, maybe I can update the code soon.

Also I don't know if the code still works since Nexmo/Vonage changed their API, if I'm not mistaken.

**Comment by darkhacknet** [comment]
> Hello, I checked the code and actually I didn't uploaded the handlers folder.
> 
> Basically you have to create a simple command handler, tell me if you need help with this, maybe I can update the code soon.
> 
> Also I don't know if the code still works since Nexmo/Vonage changed their API, if I'm not mistaken.

Hey man thanks a lot for your response. Let me take a look and if I've problems I'll let you now today.

And nexmo is still working but they dont allow spoof. But your app are not using it. So it should work as expected, i've my nexmo Account ready for test.

**Comment by darkhacknet** [comment]
> Hello, I checked the code and actually I didn't uploaded the handlers folder.
> 
> Basically you have to create a simple command handler, tell me if you need help with this, maybe I can update the code soon.
> 
> Also I don't know if the code still works since Nexmo/Vonage changed their API, if I'm not mistaken.

I really dont know how to create the command handler, yes dude please help me =/ and for the api changes dont worry I hope to fix it,  Im reading the api docs. I have a new account and number there.

**Comment by thurdev** [comment]
Hello man, I see u want to use it, let me put that on my list to do it.

Btw Nexmo now is [Vonage](https://www.vonage.com/).

Also doing a command handler is not that hard, and I don't know if the code is goin to work as it is now, because the version of discord.js that I was using is deprecated.

So yeah, I'm gonna change to  ``discord.js v13`` slash commands etc...

**Comment by darkhacknet** [comment]
> Hello man, I see u want to use it, let me put that on my list to do it.
> 
> Btw Nexmo now is [Vonage](https://www.vonage.com/).
> 
> Also doing a command handler is not that hard, and I don't know if the code is goin to work as it is now, because the version of discord.js that I was using is deprecated.
> 
> So yeah, I'm gonna change to  ``discord.js v13`` slash commands etc...

Hey man, thanks for your answer. And yes you're nexmo is vonage, I have an Account with Number ready for this and other tests. I'll ve aware of this. 🤜🤛 Thanks.

**Comment by thurdev** [comment]
New v2 not fully finished, but working.

So you can work with that and improve it (if you want to)😁

I would love to accept PR's 😊.

Any problem feel free to open again a new issue.

**Comment by darkhacknet** [comment]
> New v2 not fully finished, but working.
> 
> So you can work with that and improve it (if you want to)😁
> 
> I would love to accept PR's 😊.
> 
> Any problem feel free to open again a new issue.

Hey man thanks, of course ill take a look.
